### PR TITLE
Fix error message when using auth command with client credentials.

### PR DESCRIPTION
**Pull request by anthonyroach**
Also upgraded all dependencies to get tests and lint working.
Also updated CHANGELOG with missing 4.0.0 release.

### CODE REVIEW

**Comment by anthonyroach** [comment]
Not sure what that travis-ci failure is about. I can't see any details on it... maybe travis-ci isn't setup on this repo?

**Comment by david-wb** [comment]
Details say no rakefile found

**Comment by david-wb** [comment]
I think `travis.yml` needs to be `.travis.yml` if you want to try that

**Comment by anthonyroach** [comment]
@david-wb I see that now too... didn't see the details link. I'll give that a shot.

**Comment by anthonyroach** [comment]
@david-wb yep, that worked. Thanls.

**Pull request merged**
